import { readFileSync, writeFileSync } from 'node:fs'
const root = new URL('../', import.meta.url)
const pkg = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'))
const protocol = readFileSync(new URL('lib/protocol.js', root), 'utf8').replace(/^export /gm, '')
const client = readFileSync(new URL('src/client.js', root), 'utf8').replace(/^export /gm, '').replace(/^import .*$/gm, '')
const tools = readFileSync(new URL('src/tool-fold.js', root), 'utf8').replace(/^export /gm, '')
const folding = readFileSync(new URL('src/folding.js', root), 'utf8').replace(/^export /gm, '')
const settings = readFileSync(new URL('src/settings-ui.js', root), 'utf8').replace(/^export /gm, '')
writeFileSync(new URL('lib/client.js', root), `// Generated by scripts/build-client.mjs; edit src/client.js or lib/protocol.js.\nwindow.__ModuleLoader__.load({id:'${pkg.name}',factory(require){\n${protocol}\n${folding}\n${tools}\n${settings}\n${client}\nreturn createClient(require('react'), { scanProgressSpans, progressSegments, withoutProgress });\n}});\n`)
